### ISSUE TITLE
Examples don't fit to actual getl-version

### ISSUE THREAD

**Issue by skydive241** [ascrus/getl#9]
Hi!

* The examples don't fit any longer to the actual getl-version (at least init\GenerateData.groovy throws some errors...),

* Dependency super-csv-xxx.jar is missing in libs directory.

* Using older getl distribution, ./init/GenerateData.groovy stops with the following error:

Value too long for column "VALUE_1_2 DECIMAL(9, 2) SELECTIVITY 100": "10000000.00 (10)"; SQL statement:
INSERT INTO "DATA" ("SEQ_ID","SOURCE_ID","NAME","DT","FLAG","VALUE_1","VALUE_2","VALUE_3","VALUE_4","VALUE_5","VALUE_6","VALUE_7","VALUE_8","VALUE_9","VALUE_1_2")
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [22001-194]

Greetings from Germany,
Patrick

**Comment by ascrus** [comment]
Hi Patrick.

Sorry, at the moment examples are not relevant.

In the near future to prepare for the release of version 4 of GETL with support for DSL language management of ETL processes. Inside the source code there will be a packet with scripts of examples of working with all data sources and demonstrating the possibilities of working with them using GETL.

Also, examples of the work of objects GETL can be seen in the source code of unit tests.
